{{ if .Values.mastodon.cron.removeMedia.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "mastodon.fullname" . }}-media-remove
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.mastodon.cron.removeMedia.schedule }}
  jobTemplate:
    spec:
      template:
        metadata:
          name: {{ include "mastodon.fullname" . }}-media-remove
          {{- with .Values.jobAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: postgres-root-ca
              secret:
                secretName: {{ template "mastodon.postgresql.fullname" . }}
                optional: yes
          containers:
            - name: {{ include "mastodon.fullname" . }}-media-remove
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - bin/tootctl
                - media
                - remove
              envFrom:
                - configMapRef:
                    name: {{ include "mastodon.fullname" . }}-env
                - secretRef:
                    name: {{ template "mastodon.secretName" . }}
              env:
                - name: "PORT"
                  value: {{ .Values.mastodon.web.port | quote }}
              volumeMounts:
                - name: postgres-root-ca
                  mountPath: /opt/mastodon/.postgresql
{{- end }}
