---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "mastodon.redis.fullname" . }}
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    {{- include "mastodon.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mastodon.redis.fullname" . }}
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mastodon.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "mastodon.labels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: redis:6-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis
              containerPort: 6379
          livenessProbe:
            exec:
              command:
              - redis-cli
              - ping
            initialDelaySeconds: 30
            timeoutSeconds: 5
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
