---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mastodon.fullname" . }}
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: "{{ .Values.postgresql.auth.database_url | b64enc }}"
  AWS_ACCESS_KEY_ID: "{{ .Values.mastodon.s3.access_key | b64enc }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.mastodon.s3.access_secret | b64enc }}"
  SECRET_KEY_BASE: "{{ .Values.mastodon.secrets.secret_key_base | b64enc }}"
  OTP_SECRET: "{{ .Values.mastodon.secrets.otp_secret | b64enc }}"
  VAPID_PRIVATE_KEY: "{{ .Values.mastodon.secrets.vapid.private_key | b64enc }}"
  VAPID_PUBLIC_KEY: "{{ .Values.mastodon.secrets.vapid.public_key | b64enc }}"
  ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY: "{{ .Values.mastodon.secrets.active_record.encryption_deterministic_key | b64enc }}"
  ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT: "{{ .Values.mastodon.secrets.active_record.encryption_key_derivation_salt | b64enc }}"
  ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY: "{{ .Values.mastodon.secrets.active_record.encryption_primary_key | b64enc }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mastodon.postgresql.fullname" . }}
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
type: Opaque
data:
  root.crt: "{{ .Values.postgresql.auth.root_ca | b64enc }}"
