---
apiVersion: v1
kind: Namespace
metadata:
  name: snapdrop
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snapdrop
  namespace: snapdrop
spec:
  selector:
    matchLabels:
      app: snapdrop
  replicas: 1
  template:
    metadata:
      labels:
        app: snapdrop
    spec:
      containers:
      - name: snapdrop-ui
        image: ushuz/snapdrop:ui
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      - name: snapdrop-backend
        image: ushuz/snapdrop:backend
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: snapdrop
  namespace: snapdrop
spec:
  selector:
    app: snapdrop
  ports:
    - name: snapdrop-ui
      protocol: TCP
      port: 80
      targetPort: 80
    - name: snapdrop-backend
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snapdrop
  namespace: snapdrop
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: snapdrop.q12.im
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: snapdrop
            port:
              number: 80
  - host: snapdrop.q12.im
    http:
      paths:
      - path: /server
        pathType: Prefix
        backend:
          service:
            name: snapdrop
            port:
              number: 3000
